In [39]:
import pandas as pd
import numpy as np

In [56]:
from sqlalchemy import create_engine
engine = create_engine('sqlite://')
student_productivity.to_sql('my_table', engine, index=False)
student_productivity1.to_sql('my_table1', engine, index=False)

20000

In [41]:
student_productivity = pd.read_csv(r"C:\Users\sukai\Downloads\archive (2).zip")
student_productivity.head()

,student_id,age,gender,academic_level,study_hours,self_study_hours,online_classes_hours,social_media_hours,gaming_hours,sleep_hours,...,exercise_minutes,caffeine_intake_mg,part_time_job,upcoming_deadline,internet_quality,mental_health_score,focus_index,burnout_level,productivity_score,exam_score
0,1,18,Other,High School,7.64,1.56,2.20,3.05,2.19,6.52,...,81,38,1,0,Good,10,43.05,31.77,73.65,50.16
1,2,18,Other,High School,2.21,2.22,2.10,1.65,2.55,5.97,...,111,339,0,0,Good,3,15.92,37.00,13.70,1.00
2,3,22,Male,High School,3.45,0.00,0.29,1.34,2.08,8.39,...,68,266,0,1,Good,8,27.39,34.37,45.15,18.30
3,4,17,Other,High School,5.75,2.08,3.01,2.27,2.20,6.31,...,113,480,1,1,Poor,3,22.31,77.31,20.92,9.37
4,5,19,Other,High School,6.83,1.72,3.33,2.65,0.70,8.01,...,121,24,1,0,Good,8,38.11,39.53,59.23,27.81

In [43]:
student_productivity.shape

(5000, 21)

In [51]:
print("MEAN : ", np.mean(student_productivity.study_hours))
print("MEDIAN : ", np.median(student_productivity.study_hours))
print("STANDARD DEVIATION : ", np.std(student_productivity.study_hours))

MEAN :  4.539594
MEDIAN :  4.53
STANDARD DEVIATION :  1.8214827078959608

In [44]:
household_details = pd.DataFrame({"Adults":[3, 6], "Kids":[3, 1]}, index = (["Under 80", "Under 60"]))
print(household_details)

          Adults  Kids
Under 80       3     3
Under 60       6     1

In [45]:
Grocery_list = pd.Series([6, 1, 4, 2], index = (["Eggs", "Milk", "Biscuits", "Chapati Packet"]), name = "Grocery List")
print(Grocery_list)

Eggs              6
Milk              1
Biscuits          4
Chapati Packet    2
Name: Grocery List, dtype: int64

In [17]:
query = """
SELECT * FROM my_table;
"""
sql_my_table = pd.read_sql_query(query, con=engine)
print(sql_my_table.head())

   student_id  age gender academic_level  study_hours  self_study_hours  \
0           1   18  Other    High School         7.64              1.56
1           2   18  Other    High School         2.21              2.22
2           3   22   Male    High School         3.45              0.00
3           4   17  Other    High School         5.75              2.08
4           5   19  Other    High School         6.83              1.72

   online_classes_hours  social_media_hours  gaming_hours  sleep_hours  ...  \
0                  2.20                3.05          2.19         6.52  ...
1                  2.10                1.65          2.55         5.97  ...
2                  0.29                1.34          2.08         8.39  ...
3                  3.01                2.27          2.20         6.31  ...
4                  3.33                2.65          0.70         8.01  ...

   exercise_minutes  caffeine_intake_mg  part_time_job  upcoming_deadline  \
0                81                  38              1                  0
1               111                 339              0                  0
2                68                 266              0                  1
3               113                 480              1                  1
4               121                  24              1                  0

   internet_quality mental_health_score  focus_index  burnout_level  \
0              Good                  10        43.05          31.77
1              Good                   3        15.92          37.00
2              Good                   8        27.39          34.37
3              Poor                   3        22.31          77.31
4              Good                   8        38.11          39.53

   productivity_score  exam_score
0               73.65       50.16
1               13.70        1.00
2               45.15       18.30
3               20.92        9.37
4               59.23       27.81

[5 rows x 21 columns]

In [23]:
query = """
SELECT age FROM my_table WHERE age > 18;
"""
sql_my_table = pd.read_sql_query(query, con=engine)
print(sql_my_table)

      age
0      22
1      19
2      25
3      22
4      25
...   ...
3508   21
3509   20
3510   24
3511   22
3512   22

[3513 rows x 1 columns]

In [24]:
query = """
SELECT study_hours, sleep_hours FROM my_table;
"""
sql_my_table = pd.read_sql_query(query, con=engine)
print(sql_my_table.head())

   study_hours  sleep_hours
0         7.64         6.52
1         2.21         5.97
2         3.45         8.39
3         5.75         6.31
4         6.83         8.01

In [26]:
query = """
SELECT focus_index FROM my_table WHERE focus_index BETWEEN 10 AND 30;
"""
sql_my_table = pd.read_sql_query(query, con=engine)
print(sql_my_table.head())

   focus_index
0        15.92
1        27.39
2        22.31
3        20.26
4        19.21

In [31]:
query = """
SELECT burnout_level FROM my_table where burnout_level NOT BETWEEN 30 AND 40;
"""
sql_my_table = pd.read_sql_query(query, con=engine)
print(sql_my_table.head())

   burnout_level
0          77.31
1          62.01
2          45.98
3          49.44
4          60.78

In [38]:
query = """
SELECT social_media_hours FROM my_table WHERE social_media_hours IN(2.27);
"""
sql_my_table = pd.read_sql_query(query, con=engine)
print(sql_my_table.head())

   social_media_hours
0                2.27
1                2.27
2                2.27
3                2.27
4                2.27

In [37]:
query = """
SELECT social_media_hours FROM my_table WHERE social_media_hours NOT IN(3.05);
"""
sql_my_table = pd.read_sql_query(query, con=engine)
print(sql_my_table.head())

   social_media_hours
0                1.65
1                1.34
2                2.27
3                2.65
4                4.47

In [52]:
query = """
SELECT mental_health_score FROM my_table WHERE mental_health_score>3 AND mental_health_score<10;
"""
sql_my_table = pd.read_sql_query(query, con=engine)
print(sql_my_table.head())

   mental_health_score
0                    8
1                    8
2                    8
3                    6
4                    9

In [53]:
query = """
SELECT student_id FROM my_table WHERE self_study_hours>2 OR exam_score>30;
"""
sql_my_table = pd.read_sql_query(query, con=engine)
print(sql_my_table.head())

   student_id
0           1
1           2
2           4
3           6
4           7

In [54]:
student_productivity1 = pd.read_csv(r"C:\Users\sukai\Downloads\archive (3).zip")
student_productivity1.head()

,student_id,age,gender,study_hours_per_day,sleep_hours,phone_usage_hours,social_media_hours,youtube_hours,gaming_hours,breaks_per_day,coffee_intake_mg,exercise_minutes,assignments_completed,attendance_percentage,stress_level,focus_score,final_grade,productivity_score
0,1,23,Female,4.35,3.63,3.38,2.73,1.83,5.26,6,347,111,2,57.21,10,57,81.87,33.78
1,2,20,Male,6.14,6.58,5.48,1.51,3.13,1.73,13,403,28,10,91.27,10,49,60.90,48.99
2,3,29,Female,4.98,3.26,4.83,3.63,0.18,4.71,1,419,102,8,63.14,2,38,86.22,36.60
3,4,27,Female,3.19,4.58,10.06,3.95,5.75,2.52,9,178,28,18,40.51,6,50,71.77,19.87
4,5,24,Male,7.67,6.21,3.02,1.59,5.46,5.65,8,436,105,7,45.53,6,41,90.13,52.90

In [57]:
query = """
SELECT * FROM my_table1;
"""
sql_my_table = pd.read_sql_query(query, con=engine)
print(sql_my_table.head())

   student_id  age  gender  study_hours_per_day  sleep_hours  \
0           1   23  Female                 4.35         3.63
1           2   20    Male                 6.14         6.58
2           3   29  Female                 4.98         3.26
3           4   27  Female                 3.19         4.58
4           5   24    Male                 7.67         6.21

   phone_usage_hours  social_media_hours  youtube_hours  gaming_hours  \
0               3.38                2.73           1.83          5.26
1               5.48                1.51           3.13          1.73
2               4.83                3.63           0.18          4.71
3              10.06                3.95           5.75          2.52
4               3.02                1.59           5.46          5.65

   breaks_per_day  coffee_intake_mg  exercise_minutes  assignments_completed  \
0               6               347               111                      2
1              13               403                28                     10
2               1               419               102                      8
3               9               178                28                     18
4               8               436               105                      7

   attendance_percentage  stress_level  focus_score  final_grade  \
0                  57.21            10           57        81.87
1                  91.27            10           49        60.90
2                  63.14             2           38        86.22
3                  40.51             6           50        71.77
4                  45.53             6           41        90.13

   productivity_score
0               33.78
1               48.99
2               36.60
3               19.87
4               52.90

In [58]:
query = """
SELECT student_id FROM my_table1 WHERE gender != "Male";
"""
sql_my_table = pd.read_sql_query(query, con=engine)
print(sql_my_table.head())

   student_id
0           1
1           3
2           4
3           6
4           7

In [62]:
query = """
SELECT student_id FROM my_table1 WHERE gender LIKE "Male";
"""
sql_my_table = pd.read_sql_query(query, con=engine)
print(sql_my_table.head())

   student_id
0           2
1           5
2           9
3          11
4          12

In [61]:
query = """
SELECT student_id FROM my_table1 WHERE gender NOT LIKE "Male";
"""
sql_my_table = pd.read_sql_query(query, con=engine)
print(sql_my_table.head())

   student_id
0           1
1           3
2           4
3           6
4           7

In [69]:
query = """
SELECT sleep_hours FROM my_table1 WHERE gender LIKE "Female";
"""
sql_my_table = pd.read_sql_query(query, con=engine)
print(sql_my_table.head())

   sleep_hours
0         3.63
1         3.26
2         4.58
3         6.36
4         4.86

In [70]:
query = """
SELECT gaming_hours FROM my_table1 WHERE gender LIKE "Male";
"""
sql_my_table = pd.read_sql_query(query, con=engine)
print(sql_my_table.head())

   gaming_hours
0          1.73
1          5.65
2          3.38
3          1.36
4          0.20

In [72]:
query = """
SELECT age FROM my_table1 WHERE gender LIKE "Fe%ale";
"""
sql_my_table = pd.read_sql_query(query, con=engine)
print(sql_my_table.head())

   age
0   23
1   29
2   27
3   21
4   23

In [76]:
query = """
SELECT phone_usage_hours FROM my_table1 WHERE gender LIKE "mal_";
"""
sql_my_table = pd.read_sql_query(query, con=engine)
print(sql_my_table.head())

   phone_usage_hours
0               5.48
1               3.02
2               9.66
3               7.25
4               1.56