In [1]:
import pandas as pd

In [2]:
starbucks_patterns = pd.read_csv(r"C:\Users\sukai\Downloads\archive (4).zip")
starbucks_patterns.head()

,customer_id,order_id,order_date,order_time,day_of_week,order_channel,store_id,store_location_type,region,customer_age_group,customer_gender,is_rewards_member,cart_size,num_customizations,total_spend,fulfillment_time_min,drink_category,has_food_item,order_ahead,customer_satisfaction
0,CUST_12974,ORD_00000001,2024-03-25,08:47,Mon,Drive-Thru,STR_340,Suburban,Southwest,18-24,Male,False,5,0,14.48,8.2,Refresher,False,False,4
1,CUST_08235,ORD_00000002,2025-07-18,08:02,Fri,Mobile App,STR_425,Urban,Northeast,35-44,Female,True,1,3,9.52,5.4,Brewed Coffee,False,True,4
2,CUST_00393,ORD_00000003,2025-01-15,05:40,Wed,Kiosk,STR_103,Suburban,Midwest,25-34,Female,False,2,1,9.32,4.9,Brewed Coffee,False,False,5
3,CUST_06936,ORD_00000004,2024-07-30,15:10,Tue,Drive-Thru,STR_318,Suburban,Midwest,25-34,Female,True,2,1,9.55,3.5,Refresher,False,False,4
4,CUST_09800,ORD_00000005,2024-06-18,07:38,Tue,Drive-Thru,STR_338,Suburban,Northeast,35-44,Female,False,3,1,12.24,4.1,Frappuccino,False,False,3

In [4]:
starbucks_patterns.num_customizations.dtype

dtype('int64')

In [5]:
starbucks_patterns.dtypes

customer_id               object
order_id                  object
order_date                object
order_time                object
day_of_week               object
order_channel             object
store_id                  object
store_location_type       object
region                    object
customer_age_group        object
customer_gender           object
is_rewards_member           bool
cart_size                  int64
num_customizations         int64
total_spend              float64
fulfillment_time_min     float64
drink_category            object
has_food_item               bool
order_ahead                 bool
customer_satisfaction      int64
dtype: object

In [6]:
starbucks_patterns.cart_size.astype("float64")

0        5.0
1        1.0
2        2.0
3        2.0
4        3.0
        ...
99995    4.0
99996    5.0
99997    3.0
99998    5.0
99999    1.0
Name: cart_size, Length: 100000, dtype: float64

In [7]:
starbucks_patterns.customer_satisfaction.isnull()

0        False
1        False
2        False
3        False
4        False
         ...
99995    False
99996    False
99997    False
99998    False
99999    False
Name: customer_satisfaction, Length: 100000, dtype: bool

In [8]:
starbucks_patterns.drink_category.fillna("Unknown")

0            Refresher
1        Brewed Coffee
2        Brewed Coffee
3            Refresher
4          Frappuccino
             ...
99995      Frappuccino
99996         Espresso
99997         Espresso
99998            Other
99999    Brewed Coffee
Name: drink_category, Length: 100000, dtype: object

In [9]:
starbucks_patterns.customer_satisfaction.replace(4, 5)

0        5
1        5
2        5
3        5
4        3
        ..
99995    5
99996    3
99997    1
99998    2
99999    5
Name: customer_satisfaction, Length: 100000, dtype: int64

In [30]:
student_productivity = pd.read_csv(r"C:\Users\sukai\Downloads\archive (2).zip")
student_productivity.head()

,student_id,age,gender,academic_level,study_hours,self_study_hours,online_classes_hours,social_media_hours,gaming_hours,sleep_hours,...,exercise_minutes,caffeine_intake_mg,part_time_job,upcoming_deadline,internet_quality,mental_health_score,focus_index,burnout_level,productivity_score,exam_score
0,1,18,Other,High School,7.64,1.56,2.20,3.05,2.19,6.52,...,81,38,1,0,Good,10,43.05,31.77,73.65,50.16
1,2,18,Other,High School,2.21,2.22,2.10,1.65,2.55,5.97,...,111,339,0,0,Good,3,15.92,37.00,13.70,1.00
2,3,22,Male,High School,3.45,0.00,0.29,1.34,2.08,8.39,...,68,266,0,1,Good,8,27.39,34.37,45.15,18.30
3,4,17,Other,High School,5.75,2.08,3.01,2.27,2.20,6.31,...,113,480,1,1,Poor,3,22.31,77.31,20.92,9.37
4,5,19,Other,High School,6.83,1.72,3.33,2.65,0.70,8.01,...,121,24,1,0,Good,8,38.11,39.53,59.23,27.81

In [29]:
student_productivity = pd.read_csv(r"C:\Users\sukai\Downloads\archive (3).zip")
student_productivity.head()

,student_id,age,gender,study_hours_per_day,sleep_hours,phone_usage_hours,social_media_hours,youtube_hours,gaming_hours,breaks_per_day,coffee_intake_mg,exercise_minutes,assignments_completed,attendance_percentage,stress_level,focus_score,final_grade,productivity_score
0,1,23,Female,4.35,3.63,3.38,2.73,1.83,5.26,6,347,111,2,57.21,10,57,81.87,33.78
1,2,20,Male,6.14,6.58,5.48,1.51,3.13,1.73,13,403,28,10,91.27,10,49,60.90,48.99
2,3,29,Female,4.98,3.26,4.83,3.63,0.18,4.71,1,419,102,8,63.14,2,38,86.22,36.60
3,4,27,Female,3.19,4.58,10.06,3.95,5.75,2.52,9,178,28,18,40.51,6,50,71.77,19.87
4,5,24,Male,7.67,6.21,3.02,1.59,5.46,5.65,8,436,105,7,45.53,6,41,90.13,52.90

In [27]:
from sqlalchemy import create_engine
engine = create_engine('sqlite://')
student_productivity.to_sql('my_table', engine, index=False)
student_productivity1.to_sql('my_table1', engine, index=False)

20000

In [20]:
query = """
SELECT t1.academic_level, t2.gender FROM my_table t1
INNER JOIN my_table1 t2
ON t1.student_id = t2.student_id;
"""
sql_my_table = pd.read_sql_query(query, con=engine)
print(sql_my_table.head())

  academic_level  gender
0    High School  Female
1    High School    Male
2    High School  Female
3    High School  Female
4    High School    Male

In [23]:
query = """
SELECT DISTINCT t1.burnout_level, t2.breaks_per_day FROM my_table t1
INNER JOIN my_table1 t2
ON t1.student_id = t2.student_id
ORDER BY burnout_level ASC
LIMIT 10 OFFSET 10;
"""
sql_my_table = pd.read_sql_query(query, con=engine)
print(sql_my_table.head())

   burnout_level  breaks_per_day
0           7.07              13
1           8.43              13
2           8.59              11
3           8.66               5
4           8.80               2

In [25]:
query = """
SELECT t1.exercise_minutes, t2.coffee_intake_mg, t2.breaks_per_day FROM my_table t1
INNER JOIN my_table1 t2
ON t1.student_id = t2.student_id
WHERE breaks_per_day > 5
ORDER BY burnout_level DESC
LIMIT 10 OFFSET 10;
"""
sql_my_table = pd.read_sql_query(query, con=engine)
print(sql_my_table.head())

   exercise_minutes  coffee_intake_mg  breaks_per_day
0                 3                45               8
1                30               297               7
2                 2                37              13
3                 8               199              10
4                64                 7               8

In [31]:
query = """
SELECT t1.academic_level, t2.study_hours_per_day FROM my_table t1
INNER JOIN my_table1 t2
ON t1.student_id = t2.student_id
WHERE mental_health_score > 5
ORDER BY burnout_level DESC
LIMIT 10 OFFSET 10;
"""
sql_my_table = pd.read_sql_query(query, con=engine)
print(sql_my_table.head())

  academic_level  study_hours_per_day
0  Undergraduate                 9.87
1   Postgraduate                 7.96
2   Postgraduate                 1.22
3  Undergraduate                 8.77
4    High School                 0.87